version: '3.3'
services:
  database:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=dxpcloud
      - MYSQL_PASSWORD=dxpcloud
    ports:
      - "127.0.0.1:33060:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
  liferay:
    build:
      context: ./liferay/build/docker
    environment:
      - LIFERAY_JAVA_OPTS=-Xms4g -Xmx4g
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - JAVA_OPTS=-agentpath:/lib/libjrebel64.so -javaagent:/xrebel.jar -Drebel.remoting_plugin=true -Drebel.log.file=/jrebel.log
    ports:
      - "127.0.0.1:11311:11311"
      - "8000:8000"
    volumes:
      - ./liferay/build/docker/deploy:/opt/liferay/deploy
      - ./liferay/build/docker/work:/opt/liferay/work
      - $SIM_SCRIPT/jrebel-jar/jrebel.jar:/jrebel.jar
      - $SIM_SCRIPT/jrebel-jar/xrebel.jar:/xrebel.jar
      - $SIM_SCRIPT/jrebel-jar/lib/libjrebel64.so:/lib/libjrebel64.so
      - type: volume
        source: liferay-data
        target: /opt/liferay/data 
    depends_on:
      - database
      - search
  search:
    image: "liferaycloud/elasticsearch:6.8.13-4.1.1"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_SERVICE_SCALE=1
      - LCP_SERVICE_ID=search
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "127.0.0.1:9200:9200"
  webserver:
    image: "liferaycloud/nginx:1.16.1-4.1.1"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - liferay
volumes:
  liferay-data:
  database-data:
