version: '3.3'
services:
  database:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=dxpcloud
      - MYSQL_PASSWORD=dxpcloud
    ports:
      - "127.0.0.1:33060:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
  liferay:
    build:
      context: ./liferay/build/docker
    environment:
      - LIFERAY_JAVA_OPTS=-Xms4g -Xmx4g
      - LIFERAY_JPDA_ENABLED=true # Enable Debug remote property
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
    ports:
      - "127.0.0.1:11311:11311"
      - "8000:8000" # Expose debug port
    volumes:
      - ./liferay/build/docker/deploy:/opt/liferay/deploy #Mount deploy folder
      - ./liferay/build/docker/work:/opt/liferay/work #Mount Debug JSP path
      - type: volume
        source: liferay-data
        target: /opt/liferay/data 
    depends_on:
      - database
      - search
  search:
    image: "liferaycloud/elasticsearch:6.8.13-4.1.1"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_SERVICE_SCALE=1
      - LCP_SERVICE_ID=search
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9200:9200"
  kibana:
    image: kibana:6.8.13
    environment:
      - ELASTICSEARCH_HOSTS=http://search:9200
    depends_on:
      - search
    ports:
      - 5601:5601
  webserver:
    build:
      context: ./webserver
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - liferay
volumes:
  liferay-data:
  database-data:
